### ISSUE TITLE
empty()函数用法错误（更新：PHP版本过低，5.5以上解决）

### ISSUE THREAD

**Issue by ezioxiao** [freyo/OSC4CQJTU#1]
empty()函数只检测变量，检测任何非变量的东西都将导致解析错误。
换句话说，后边的语句将不会起作用： empty(I(‘get.area'))会报错无返回值。
建议预先设定变量，然后使用empty()函数。
错误见于Admin/Controller中的Task和User，以及Home/Controller中的Report和User。

**Comment by freyo** [comment]
PHP5.5以上可解决该问题。

**Comment by ezioxiao** [comment]
原来如此，版本号也影响这么多……学习了，谢谢啦
